[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
   teemuatlut/TMCStepper@^0.7.0
   bblanchon/ArduinoJson@^6.21
   bblanchon/ContinuousStepper @ ^3.1.0
   plerup/EspSoftwareSerial @ ^8.2.0

